### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by 123abxc** [Liling-yang/LENFsuion#1]
能方便问下训练的设备内存吗 在训练时总是pycharm闪退内存不足

**Comment by Liling-yang** [comment]
train.py中的train_enhance() 是2438MiB，train_fusion() 是15420MiB；
LFN_train.py是3672MiB；
所以完整训练整个网络结构显存至少要大于15420MiB

**Comment by 123abxc** [comment]
好的谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Liling Yang ***@***.***&gt;
发送时间: 2024年5月15日 16:15
收件人: Liling-yang/LENFsuion ***@***.***&gt;
抄送: 123abxc ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Liling-yang/LENFsuion] 训练 (Issue #1)





 
train.py中的train_enhance() 是2438MiB，train_fusion() 是15420MiB；
 LFN_train.py是3672MiB；
 所以完整训练整个网络结构显存至少要大于15420MiB
